/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;

// Paquetes a utilizar
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color; // Importa la clase Color para manejar colores
import java.awt.Image; // Importa la clase Image para trabajar con imágenes
import java.awt.Toolkit; // Importa la clase Toolkit para obtener imágenes del sistema
import java.io.FileOutputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane; // Importa JOptionPane para mostrar cuadros de diálogo
import java.sql.*;
import com.itextpdf.text.*;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author canto
 */
public class JFAdministrarDonaciones extends javax.swing.JFrame {

    /**
     * Creates new form JFAdministrarDonaciones
     */
    
    public JFAdministrarDonaciones() {
        initComponents(); // Método que configura y organiza todos los componentes gráficos en la ventana.
        setIconImage(getIconImage()); // Establece un ícono personalizado para la ventana.
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Desactiva la X de cierre
    }
    //Icono del JFrame
    @Override // Indica que este método sobrescribe el método getIconImage() de la clase JFrame
    // Usa Toolkit (una clase de utilidades gráficas de AWT) para obtener una imagen ubicada en la ruta interna del proyecto
    // ClassLoader.getSystemResource() localiza el archivo dentro del classpath (dentro de src o el .jar).
    public Image getIconImage(){ 
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("workshopadmin/Imagenes/LogoIcono.png"));
        return retValue; // Devuelve la imagen para que sea usada como ícono del JFrame
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelnformacion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonRegistrarDonaciones = new javax.swing.JButton();
        jButtonHistorial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar donantes");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelnformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Informacion.png"))); // NOI18N
        jLabelnformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelnformacionMouseClicked(evt);
            }
        });

        jButtonRegistrarDonaciones.setBackground(java.awt.Color.lightGray);
        jButtonRegistrarDonaciones.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonRegistrarDonaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Pagos_1.png"))); // NOI18N
        jButtonRegistrarDonaciones.setText("<html>Registrar donaciones</html>");
        jButtonRegistrarDonaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegistrarDonacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegistrarDonacionesMouseExited(evt);
            }
        });
        jButtonRegistrarDonaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarDonacionesActionPerformed(evt);
            }
        });

        jButtonHistorial.setBackground(java.awt.Color.lightGray);
        jButtonHistorial.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Historial.png"))); // NOI18N
        jButtonHistorial.setText("Historial");
        jButtonHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHistorialMouseExited(evt);
            }
        });
        jButtonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegistrarDonaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButtonRegistrarDonaciones)
                .addGap(49, 49, 49)
                .addComponent(jButtonHistorial)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Administra las donaciones");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Imagenes/Pagos.png"))); // NOI18N

        jButtonRegresar.setBackground(java.awt.Color.lightGray);
        jButtonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Atras.png"))); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseExited(evt);
            }
        });
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonRegresar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jLabelnformacion)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelnformacion))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jButtonRegresar)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelnformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelnformacionMouseClicked
        // TODO add your handling code here:
        // Este método se ejecuta cuando el usuario hace clic en el label de información.
        JOptionPane.showMessageDialog(null,"Selecciona la acción que deseas realizar respecto a las donaciones",
            "Información",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelnformacionMouseClicked

    private void jButtonRegistrarDonacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarDonacionesMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonRegistrarDonaciones.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonRegistrarDonacionesMouseEntered

    private void jButtonRegistrarDonacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarDonacionesMouseExited
        // TODO add your handling code here:
        jButtonRegistrarDonaciones.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonRegistrarDonacionesMouseExited

    private void jButtonRegistrarDonacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarDonacionesActionPerformed
        // TODO add your handling code here:
        JFRegistrarDonaciones JFRegistrarDonaciones =new JFRegistrarDonaciones(); // Llama a la ventana de modificar
        JFRegistrarDonaciones.setVisible(true); // Muestra la ventana
        JFRegistrarDonaciones.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setVisible(false); // Oculta la ventana actual
    }//GEN-LAST:event_jButtonRegistrarDonacionesActionPerformed

    private void jButtonHistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistorialMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonHistorial.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonHistorialMouseEntered

    private void jButtonHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistorialMouseExited
        // TODO add your handling code here:
        // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonHistorial.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonHistorialMouseExited

    private void jButtonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonRegresar.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonRegresarMouseEntered

    private void jButtonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseExited
        // TODO add your handling code here:
        // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonRegresar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonRegresarMouseExited

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        JFMenuAdministrador JFMenuAdministrador =new JFMenuAdministrador(); // Llama a la ventana de modificar
        JFMenuAdministrador.setVisible(true); // Muestra la ventana
        JFMenuAdministrador.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setVisible(false); // Oculta la ventana actual
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistorialActionPerformed
    // TODO add your handling code here: 
    // Atributos de conexión
    String bd = "workshopadmin"; // Nombre de la base de datos
    String url = "jdbc:mysql://localhost:3306/" + bd; // URL de conexión a la base de datos MySQL en localhost
    String user = "root"; // Usuario de la base de datos
    String password = "sqloracle"; // Contraseña del usuario
    String driver = "com.mysql.cj.jdbc.Driver"; // Driver JDBC para MySQL

    // Declaración de objetos para conexión, consulta y resultados
    java.sql.Connection cx = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    try {
        Class.forName(driver); // Carga el driver JDBC
        cx = DriverManager.getConnection(url, user, password); // Establece la conexión con la base de datos

        // Consulta para obtener historial de donaciones con nombres de grupo y taller
        String sql = "SELECT d.id_donacion, d.nombre AS nombre_donante, d.apellido AS apellido_donante, " +
                     "d.monto, d.fecha_donacion, g.nombre AS nombre_grupo, t.nombre AS nombre_taller " +
                     "FROM donaciones d " +
                     "JOIN grupos g ON d.id_grupo = g.id_grupo " +
                     "JOIN talleres t ON g.id_taller = t.id_taller " +
                     "ORDER BY d.fecha_donacion DESC";

        // Prepara la consulta con soporte para desplazamiento y solo lectura
        ps = cx.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = ps.executeQuery();

        // Obtiene la ruta de descargas del usuario
        String userHome = System.getProperty("user.home");
        String downloadPath = userHome + "/Downloads/";
        String filePath = downloadPath + "HistorialDonaciones.pdf";

        // Crear documento PDF
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(filePath));
        document.open();
        
        // Formato de fecha y hora en español para la fecha de "Generado" con formato de 24 horas
        SimpleDateFormat sdfGenerado = new SimpleDateFormat("dd MMMM yyyy HH:mm:ss", new Locale("es", "ES"));
        String fechaGenerado = sdfGenerado.format(new java.util.Date());
        
        // Centrar el título
        Paragraph title = new Paragraph("Historial de Donaciones", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16));
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title); // Añade el título
        document.add(new Paragraph(" ")); // Espacio en blanco
        document.add(new Paragraph("Generado: " + fechaGenerado)); // Fecha de generación
        document.add(new Paragraph(" ")); // Espacio en blanco

         // Crear tabla con 5 columnas para mostrar los datos
        PdfPTable table = new PdfPTable(5); // 5 columnas: Donante, Monto, Fecha, Grupo, Taller
        table.setWidthPercentage(100);  // Ancho completo
 
        // Cabeceras de la tabla
        table.addCell("Donante");
        table.addCell("Monto");
        table.addCell("Fecha");
        table.addCell("Grupo");
        table.addCell("Taller");

        boolean hayResultados = false; // Bandera para verificar si hay datos
        
       // Formato de fecha en español para la fecha en la tabla
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy", new Locale("es", "ES"));
         
        // Iterar sobre los resultados
        while (rs.next()) {
            hayResultados = true;
            String donante = rs.getString("nombre_donante") + " " + rs.getString("apellido_donante"); // Concatenar nombre y apellido del donante
            table.addCell(donante);
            table.addCell("$" + String.format("%.2f", rs.getDouble("monto"))); // Formatear el monto como moneda
            
            // Convertir fecha a formato en español
            String fecha = sdf.format(rs.getDate("fecha_donacion"));
            table.addCell(fecha);
            
            table.addCell(rs.getString("nombre_grupo"));
            table.addCell(rs.getString("nombre_taller"));
        }
        
         // Si no hay resultados, muestra mensaje y cierra documento
        if (!hayResultados) {
            JOptionPane.showMessageDialog(null, "No hay registros de donaciones.");
            document.close();
            return;
        }

        document.add(table);
        document.close();
        JOptionPane.showMessageDialog(null, "PDF generado exitosamente en la carpeta de descargas.");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al generar PDF: " + e.getMessage());
    } finally {
        try {
            // Cierra los recursos en caso de haber sido abiertos
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (cx != null) cx.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_jButtonHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAdministrarDonaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAdministrarDonaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAdministrarDonaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAdministrarDonaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAdministrarDonaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHistorial;
    private javax.swing.JButton jButtonRegistrarDonaciones;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelnformacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
