/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;

import Clases.Carnet;
import Clases.Conexion;
import Clases.ConsultarAlumnos; // Importa la clase ConsultarAlumnos
import Clases.TextPrompt; // Importa la clase TextPrompt para utilizar placeholders
import com.itextpdf.text.Chunk;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color; // Permite usar la clase Color para cambiar colores en componentes gráficos.
import java.awt.Desktop;
import java.awt.Image; // Permite manejar imágenes, por ejemplo, para íconos o imágenes en la interfaz.
import java.awt.Toolkit; // Proporciona acceso a recursos del sistema como imágenes, sonidos, etc.
import java.awt.event.KeyEvent; // Permite detectar y manejar eventos del teclado, como presionar, soltar o escribir una tecla.
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane; // Permite mostrar cuadros de diálogo (mensajes, confirmaciones, entradas de texto, etc.).
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel; // Permite trabajar con la tabla

/**
 *
 * @author canto
 */
public class JFConsultarAlumnos extends javax.swing.JFrame {
    private Carnet carnetGen;
    /**
     * Creates new form JFConsultarAlumno
     */
    
    public JFConsultarAlumnos() {
        initComponents(); // Método que configura y organiza todos los componentes gráficos en la ventana.
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Desactiva la X de cierre
        
        TextPrompt matricula = new TextPrompt("22070065",jTextMatricula); // Establece textos de sugerencia ("placeholders")
        
        setIconImage(getIconImage()); // Establece un ícono personalizado para la ventana.
    }
    //Icono del JFrame
    @Override // Indica que este método sobrescribe el método getIconImage() de la clase JFrame
    // Usa Toolkit (una clase de utilidades gráficas de AWT) para obtener una imagen ubicada en la ruta interna del proyecto
    // ClassLoader.getSystemResource() localiza el archivo dentro del classpath (dentro de src o el .jar).
    public Image getIconImage(){ 
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("workshopadmin/Imagenes/LogoIcono.png"));
        return retValue; // Devuelve la imagen para que sea usada como ícono del JFrame
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRegresar = new javax.swing.JButton();
        jButtonRegresarInicio = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelnformacion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextContactoTutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonConsultarActivo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        jTextNombres = new javax.swing.JTextField();
        jTextEdad = new javax.swing.JTextField();
        jTextTutor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextApellidos = new javax.swing.JTextField();
        jButtonHistorial = new javax.swing.JButton();
        jButtonGenerarCredencial = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTalleresGrupos = new javax.swing.JTable();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonConsultarInactivo = new javax.swing.JButton();
        jButtonImprimirCredencial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consula de alumnos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonRegresar.setBackground(java.awt.Color.lightGray);
        jButtonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Atras.png"))); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseExited(evt);
            }
        });
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jButtonRegresarInicio.setBackground(java.awt.Color.lightGray);
        jButtonRegresarInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonRegresarInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Atras.png"))); // NOI18N
        jButtonRegresarInicio.setText("Regresar al inicio");
        jButtonRegresarInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegresarInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegresarInicioMouseExited(evt);
            }
        });
        jButtonRegresarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarInicioActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Imagenes/Alumno.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Consulta un alumno");

        jLabelnformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Informacion.png"))); // NOI18N
        jLabelnformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelnformacionMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Matrícula");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nombres");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Edad");

        jTextContactoTutor.setEditable(false);
        jTextContactoTutor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Tutor");

        jButtonConsultarActivo.setBackground(java.awt.Color.lightGray);
        jButtonConsultarActivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonConsultarActivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Buscar_1.png"))); // NOI18N
        jButtonConsultarActivo.setText("<html>Consultar Activo</html>");
        jButtonConsultarActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonConsultarActivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonConsultarActivoMouseExited(evt);
            }
        });
        jButtonConsultarActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActivoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Contacto");

        jTextMatricula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextMatriculaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextMatriculaKeyTyped(evt);
            }
        });

        jTextNombres.setEditable(false);
        jTextNombres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextEdad.setEditable(false);
        jTextEdad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextTutor.setEditable(false);
        jTextTutor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Apellidos");

        jTextApellidos.setEditable(false);
        jTextApellidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButtonHistorial.setBackground(java.awt.Color.lightGray);
        jButtonHistorial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Historial.png"))); // NOI18N
        jButtonHistorial.setText("Historial");
        jButtonHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHistorialMouseExited(evt);
            }
        });
        jButtonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistorialActionPerformed(evt);
            }
        });

        jButtonGenerarCredencial.setBackground(java.awt.Color.lightGray);
        jButtonGenerarCredencial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonGenerarCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/GenerarCredencial.png"))); // NOI18N
        jButtonGenerarCredencial.setText("<html>Generar credencial</html>");
        jButtonGenerarCredencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonGenerarCredencialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonGenerarCredencialMouseExited(evt);
            }
        });
        jButtonGenerarCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarCredencialActionPerformed(evt);
            }
        });

        jTableTalleresGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Taller", "Grupo"
            }
        ));
        jScrollPane2.setViewportView(jTableTalleresGrupos);

        jButtonLimpiar.setBackground(java.awt.Color.lightGray);
        jButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/limpiar.png"))); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLimpiarMouseExited(evt);
            }
        });
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonConsultarInactivo.setBackground(java.awt.Color.lightGray);
        jButtonConsultarInactivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonConsultarInactivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Buscar_1.png"))); // NOI18N
        jButtonConsultarInactivo.setText("<html>Consultar Inactivo</html>");
        jButtonConsultarInactivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonConsultarInactivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonConsultarInactivoMouseExited(evt);
            }
        });
        jButtonConsultarInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarInactivoActionPerformed(evt);
            }
        });

        jButtonImprimirCredencial.setBackground(java.awt.Color.lightGray);
        jButtonImprimirCredencial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonImprimirCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/imprimir.png"))); // NOI18N
        jButtonImprimirCredencial.setText("<html>Imprimir credencial</html>");
        jButtonImprimirCredencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonImprimirCredencialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonImprimirCredencialMouseExited(evt);
            }
        });
        jButtonImprimirCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirCredencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextApellidos)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextContactoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonHistorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarActivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGenerarCredencial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarInactivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonImprimirCredencial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonConsultarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultarInactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonHistorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGenerarCredencial)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonImprimirCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiar)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextContactoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRegresarInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                        .addComponent(jLabelnformacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegresar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegresarInicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelnformacion)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonRegresar.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonRegresarMouseEntered

    private void jButtonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseExited
        // TODO add your handling code here:
         // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonRegresar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonRegresarMouseExited

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        JFAdministrarAlumnos JFAdministrarAlumnos =new JFAdministrarAlumnos(); // Crea una nueva instancia
        JFAdministrarAlumnos.setVisible(true); // Muestra la ventana de inicio
        JFAdministrarAlumnos.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setVisible(false); // Oculta la ventana actual.
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonRegresarInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarInicioMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonRegresarInicio.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonRegresarInicioMouseEntered

    private void jButtonRegresarInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarInicioMouseExited
        // TODO add your handling code here:
         // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonRegresarInicio.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonRegresarInicioMouseExited

    private void jButtonRegresarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarInicioActionPerformed
        // TODO add your handling code here:
        JFMenuAdministrador JFMenuAdministrador =new JFMenuAdministrador(); // Crea una nueva instancia
        JFMenuAdministrador.setVisible(true); // Muestra la ventana de inicio 
        JFMenuAdministrador.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setVisible(false); // Oculta la ventana actual.
    }//GEN-LAST:event_jButtonRegresarInicioActionPerformed

    private void jLabelnformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelnformacionMouseClicked
        // TODO add your handling code here:
        // Este método se ejecuta cuando el usuario hace clic en el label de información.
        JOptionPane.showMessageDialog(null,"Escribe la matricula del alumno que deseas consultar"
                + "\nPuedes usar Enter para consultar alumnos activos",
            "Información",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelnformacionMouseClicked

    private void jButtonConsultarActivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarActivoMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonConsultarActivo.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonConsultarActivoMouseEntered

    private void jButtonConsultarActivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarActivoMouseExited
        // TODO add your handling code here:
         // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonConsultarActivo.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonConsultarActivoMouseExited

    private void jButtonConsultarActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActivoActionPerformed
        // TODO add your handling code here:
        // Muestra un cuadro de diálogo para confirmar si el usuario realmente desea 
        int respuesta = JOptionPane.showConfirmDialog(null, "Realmente desea consultar a este alumno?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.NO_OPTION) {
            // Si el usuario elige "No", simplemente no hace nada o muestra otro mensaje
            JOptionPane.showMessageDialog(null, "Operación cancelada.");
            } else {
                // Validación: Verifica si algún campo obligatorio está vacío o si no se ha seleccionado taller y grupo
            if (jTextMatricula.getText().trim().isEmpty()){ 
            
            JOptionPane.showMessageDialog(null,"Por favor, escribe una matrícula",
                        "ADVERTENCIA",
                        JOptionPane.ERROR_MESSAGE);
            } else {
            ConsultarAlumnos ca = new ConsultarAlumnos();
            ca.Consultar(jTextMatricula, jTextNombres, jTextApellidos, jTextEdad, jTextTutor, jTextContactoTutor, jTableTalleresGrupos);          
            }    
        }
    }//GEN-LAST:event_jButtonConsultarActivoActionPerformed

    private void jButtonHistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistorialMouseEntered
        // TODO add your handling code here:
         // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonHistorial.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonHistorialMouseEntered

    private void jButtonHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistorialMouseExited
        // TODO add your handling code here:
        // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonHistorial.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonHistorialMouseExited

    private void jButtonGenerarCredencialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGenerarCredencialMouseEntered
        // TODO add your handling code here:
         // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonGenerarCredencial.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonGenerarCredencialMouseEntered

    private void jButtonGenerarCredencialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGenerarCredencialMouseExited
        // TODO add your handling code here:
        // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonGenerarCredencial.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonGenerarCredencialMouseExited

    private void jButtonConsultarInactivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarInactivoMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonConsultarInactivo.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonConsultarInactivoMouseEntered

    private void jButtonConsultarInactivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarInactivoMouseExited
        // TODO add your handling code here:
        // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonConsultarInactivo.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonConsultarInactivoMouseExited

    private void jButtonConsultarInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarInactivoActionPerformed
        // TODO add your handling code here:
        // Muestra un cuadro de diálogo para confirmar si el usuario realmente desea 
        int respuesta = JOptionPane.showConfirmDialog(null, "Realmente desea consultar este alumno dado de baja?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.NO_OPTION) {
            // Si el usuario elige "No", simplemente no hace nada o muestra otro mensaje
            JOptionPane.showMessageDialog(null, "Operación cancelada.");
            } else {
            // Validación: Verifica si algún campo obligatorio está vacío o si no se ha seleccionado taller y grupo
            if (jTextMatricula.getText().trim().isEmpty()){ 
            
            JOptionPane.showMessageDialog(null,"Por favor, escribe una matrícula",
                        "ADVERTENCIA",
                        JOptionPane.ERROR_MESSAGE);
            } else {
            ConsultarAlumnos ca = new ConsultarAlumnos();
            ca.ConsultarInactivo(jTextMatricula, jTextNombres, jTextApellidos, jTextEdad, jTextTutor, jTextContactoTutor, jTableTalleresGrupos);    
            }
        }
    }//GEN-LAST:event_jButtonConsultarInactivoActionPerformed

    private void jTextMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMatriculaKeyTyped
        // TODO add your handling code here:
        //Validamos que en el campo no se puedan ingresar letras.
        char c = evt.getKeyChar(); //llamamos al evento
            if (Character.isLetter(c)){ //comparamos si ingresamos una letra
                evt.consume(); //evitar que se capture la letra
                JOptionPane.showMessageDialog(null,"Solo puedes ingresar números en este campo",
                        "ADVERTENCIA",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextMatriculaKeyTyped

    private void jTextMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMatriculaKeyPressed
            // TODO add your handling code here:
            //Presiona enter para consultar alumnos activos
            // Validación: Verifica si algún campo obligatorio está vacío 
            if(evt.getKeyCode()==KeyEvent.VK_ENTER)
                {
                if (jTextMatricula.getText().trim().isEmpty()){ 

                JOptionPane.showMessageDialog(null,"Por favor, escribe una matrícula",
                            "ADVERTENCIA",
                            JOptionPane.ERROR_MESSAGE);
                } else {

                      ConsultarAlumnos ca = new ConsultarAlumnos();
                      ca.Consultar(jTextMatricula, jTextNombres, jTextApellidos, jTextEdad, jTextTutor, jTextContactoTutor, jTableTalleresGrupos); 
                    }
            }
    }//GEN-LAST:event_jTextMatriculaKeyPressed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        // Limpiar campos
        jTextMatricula.setText("");
        jTextNombres.setText("");
        jTextApellidos.setText("");
        jTextEdad.setText("");
        jTextTutor.setText("");
        jTextContactoTutor.setText("");
        DefaultTableModel model = (DefaultTableModel) jTableTalleresGrupos.getModel();
        model.setRowCount(0);
        jTextMatricula.requestFocus();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonLimpiar.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonLimpiarMouseEntered

    private void jButtonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarMouseExited
        // TODO add your handling code here:
        // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonLimpiar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonLimpiarMouseExited

    private void jButtonGenerarCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarCredencialActionPerformed
        // TODO add your handling code here:
            // Validación: Verifica si algún campo obligatorio está vacío o si no se ha seleccionado taller y grupo
            if (jTextMatricula.getText().trim().isEmpty()||
                    jTextNombres.getText().trim().isEmpty()||
                    jTextApellidos.getText().trim().isEmpty()||
                    jTextEdad.getText().trim().isEmpty()||
                    jTextTutor.getText().trim().isEmpty()||
                    jTextContactoTutor.getText().trim().isEmpty()){ 
            
            JOptionPane.showMessageDialog(null,"Por favor, consulta un alumno",
                        "ADVERTENCIA",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                try {
              // Si el objeto carnetGen aún no ha sido inicializado, lo inicializamos
              if (carnetGen == null) {
                  carnetGen = new Carnet(); // Instancia la clase que maneja la generación de carnets
              }

              // Llamamos al método para generar un nuevo carnet, pasando los datos desde los campos de texto
              carnetGen.agregarCarnet(
                  jTextMatricula.getText(),      // Matricula del estudiante
                  jTextNombres.getText(),        // Nombre del estudiante
                  jTextApellidos.getText(),      // Apellido del estudiante
                  jTextTutor.getText(),          // Nombre del tutor
                  jTextContactoTutor.getText(),  // Contacto del tutor
                  jTableTalleresGrupos           // JTable de talleres y grupos
              );

              // Mostrar mensaje de éxito
              JOptionPane.showMessageDialog(this, "Credencial generada, presione imprimir para tener acceso a ella."
                      + "\nRecuerde que puede agregar más de una credencial antes de impirmir.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
          } catch (Exception ex) {
              // Captura cualquier excepción y muestra un mensaje de error
              ex.printStackTrace();
              JOptionPane.showMessageDialog(this, "Error al generar carnet: " + ex.getMessage());
                      } 
                  }
    }//GEN-LAST:event_jButtonGenerarCredencialActionPerformed

    private void jButtonImprimirCredencialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImprimirCredencialMouseEntered
        // TODO add your handling code here:
        jButtonImprimirCredencial.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonImprimirCredencialMouseEntered

    private void jButtonImprimirCredencialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImprimirCredencialMouseExited
        // TODO add your handling code here:
        jButtonImprimirCredencial.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonImprimirCredencialMouseExited

    private void jButtonImprimirCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirCredencialActionPerformed
        // TODO add your handling code here:
        if (carnetGen != null) {
            carnetGen.cerrarDocumento();
            carnetGen = null;
            JOptionPane.showMessageDialog(this, "PDF generado exitosamente en la carpeta de descargas.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
          }
    }//GEN-LAST:event_jButtonImprimirCredencialActionPerformed

    private void jButtonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistorialActionPerformed
      // Obtener la matrícula ingresada en el campo de texto jTextMatricula
        String matricula = jTextMatricula.getText().trim(); 

        // Validación: Verifica si algún campo obligatorio está vacío o si no se ha seleccionado taller y grupo
            if (jTextMatricula.getText().trim().isEmpty()||
                    jTextNombres.getText().trim().isEmpty()||
                    jTextApellidos.getText().trim().isEmpty()||
                    jTextEdad.getText().trim().isEmpty()||
                    jTextTutor.getText().trim().isEmpty()||
                    jTextContactoTutor.getText().trim().isEmpty()){ 
            
            JOptionPane.showMessageDialog(null,"Por favor, consulta un alumno",
                        "ADVERTENCIA",
                        JOptionPane.ERROR_MESSAGE);
            } else {
        // Crear una nueva instancia de la clase Conexion para establecer conexión con la base de datos
        Conexion conexion = new Conexion();
        Connection conn = conexion.conectar(); // Establece la conexión a la base de datos

        // Si no se pudo conectar a la base de datos, mostrar un mensaje de error y salir
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "No se pudo establecer conexión con la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detiene la ejecución si no se pudo conectar
        }

        try {
            // Consulta SQL para obtener el historial del alumno con base en la matrícula
            String sql = "SELECT a.nombre, a.apellido, a.edad, a.tutor, a.contacto_tutor, g.nombre AS grupo, t.nombre AS taller, p.monto, p.fecha_pago, p.motivo "
                       + "FROM alumnos a "
                       + "JOIN grupos g ON a.id_grupo = g.id_grupo "
                       + "JOIN talleres t ON g.id_taller = t.id_taller "
                       + "LEFT JOIN pagos p ON a.id_alumno = p.id_alumno "
                       + "WHERE a.matricula = ? AND a.activo = TRUE"; // Busca los datos del alumno y sus pagos
            PreparedStatement stmt = conn.prepareStatement(sql); // Prepara la consulta
            stmt.setString(1, matricula); // Establece el valor de la matrícula en la consulta SQL

            // Ejecutar la consulta y obtener el resultado
            ResultSet rs = stmt.executeQuery();

            // Crear el documento PDF
            com.itextpdf.text.Document document = new com.itextpdf.text.Document(); // Crea un documento en blanco
            // Obtener la ruta a la carpeta Descargas del usuario
            String userHome = System.getProperty("user.home");
            File fileToSave = new File(userHome + File.separator + "Downloads" + File.separator + "Historial_" + matricula + ".pdf");

                // Crear el escritor de PDF y asociarlo con el archivo de salida
              PdfWriter.getInstance(document, new FileOutputStream(fileToSave));
              document.open(); // Abre el documento para agregar contenido

                // Añadir un título al PDF
                Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD); // Define el formato del título
                Paragraph title = new Paragraph("Historial de Alumno - Matrícula: " + matricula, titleFont); // Crea el título
                title.setAlignment(Element.ALIGN_CENTER); // Centra el título
                document.add(title); // Añadir el título al documento
                document.add(new Chunk("\n")); // Agrega un salto de línea

                // Si se encuentran datos del alumno en la base de datos
                if (rs.next()) {
                    // Agregar información del alumno al PDF
                    Paragraph alumnoInfo = new Paragraph("Nombre: " + rs.getString("nombre") + " " + rs.getString("apellido"));
                    document.add(alumnoInfo); // Añadir nombre del alumno
                    Paragraph edadInfo = new Paragraph("Edad: " + rs.getInt("edad"));
                    document.add(edadInfo); // Añadir edad del alumno
                    Paragraph tutorInfo = new Paragraph("Tutor: " + rs.getString("tutor"));
                    document.add(tutorInfo); // Añadir nombre del tutor
                    Paragraph contactoTutorInfo = new Paragraph("Contacto Tutor: " + rs.getString("contacto_tutor"));
                    document.add(contactoTutorInfo); // Añadir contacto del tutor

                    // Agregar espacio antes de la tabla (se añaden dos saltos de línea)
                    document.add(new Chunk("\n"));
                    
                    // Primero agregar la tabla de talleres y grupos
                    PdfPTable tablaTalleresGruposPDF = crearTablaDesdeJTable(jTableTalleresGrupos); // tu JTable real
                    document.add(tablaTalleresGruposPDF);
                    document.add(new Chunk("\n\n"));

                    // Crear una tabla en el PDF con tres columnas: Motivo, Monto y Fecha de Pago
                    PdfPTable table = new PdfPTable(3); // Definir el número de columnas
                    table.addCell("Motivo"); // Título de la primera columna
                    table.addCell("Monto"); // Título de la segunda columna
                    table.addCell("Fecha de Pago"); // Título de la tercera columna

                    do {
                    String motivo = rs.getString("motivo");
                    double monto = rs.getDouble("monto");
                    Date fechaPago = rs.getDate("fecha_pago");

                    // Verificar que al menos uno de los campos tenga un valor real antes de agregar a la tabla
                    if ((motivo != null && !motivo.trim().isEmpty()) || monto != 0.0 || fechaPago != null) {
                        table.addCell(motivo != null ? motivo : "Sin motivo");
                        table.addCell(String.valueOf(monto));
                        table.addCell(fechaPago != null ? fechaPago.toString() : "Sin fecha");
                    }
                } while (rs.next());

                    // Añadir la tabla al documento PDF
                    document.add(table);
                } else {
                    // Si no se encuentran datos, mostrar un mensaje en el PDF
                    document.add(new Paragraph("No se encontraron registros para esta matrícula."));
                }

                // Cerrar el documento y finalizar el archivo PDF
                document.close();
              // Mostrar un mensaje de éxito
              JOptionPane.showMessageDialog(this, "PDF generado exitosamente en la carpeta de descargas.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
      } catch (Exception e) {
          // Si ocurre un error en cualquier parte del proceso, mostrar un mensaje de error
          JOptionPane.showMessageDialog(this, "Error al generar el historial: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      } finally {
          // Desconectar de la base de datos
          conexion.desconectar();
        }
      }
    }//GEN-LAST:event_jButtonHistorialActionPerformed
public PdfPTable crearTablaDesdeJTable(JTable jTable) {
    PdfPTable table = new PdfPTable(jTable.getColumnCount());
    table.setWidthPercentage(100);

    Font fontCabecera = new Font(Font.FontFamily.HELVETICA, 8, Font.BOLD);
    Font fontCelda = new Font(Font.FontFamily.HELVETICA, 8);

    // Encabezados
    for (int i = 0; i < jTable.getColumnCount(); i++) {
        PdfPCell header = new PdfPCell(new Phrase(jTable.getColumnName(i), fontCabecera));
        header.setHorizontalAlignment(Element.ALIGN_CENTER);
        header.setPadding(3f);
        table.addCell(header);
    }

    // Filas
    for (int row = 0; row < jTable.getRowCount(); row++) {
        for (int col = 0; col < jTable.getColumnCount(); col++) {
            Object value = jTable.getValueAt(row, col);
            PdfPCell cell = new PdfPCell(new Phrase(value != null ? value.toString() : "", fontCelda));
            cell.setPadding(2f);
            table.addCell(cell);
        }
    }

    return table;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConsultarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConsultarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConsultarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConsultarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConsultarAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarActivo;
    private javax.swing.JButton jButtonConsultarInactivo;
    private javax.swing.JButton jButtonGenerarCredencial;
    private javax.swing.JButton jButtonHistorial;
    private javax.swing.JButton jButtonImprimirCredencial;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonRegresarInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelnformacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTalleresGrupos;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextContactoTutor;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextTutor;
    // End of variables declaration//GEN-END:variables
}
