/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicios;

// Paquetes a utilizar
import java.awt.Color; // Permite usar la clase Color para cambiar colores en componentes gráficos.
import java.awt.Image; // Permite manejar imágenes, por ejemplo, para íconos o imágenes en la interfaz.
import java.awt.Toolkit; // Proporciona acceso a recursos del sistema como imágenes, sonidos, etc.
import java.awt.event.WindowAdapter; // Clase que se puede extender para manejar eventos de ventana sin implementar todos los métodos.
import java.awt.event.WindowEvent; // Representa un evento que ocurre en una ventana, como cerrar, abrir, minimizar, etc.
import javax.swing.JOptionPane; // Permite mostrar cuadros de diálogo (mensajes, confirmaciones, entradas de texto, etc.).

/**
 *
 * @author canto
 */
public class JFInicioGeneral extends javax.swing.JFrame {

    /**
     * Creates new form JFInicio
     */
    public JFInicioGeneral() {
        initComponents(); // Método que configura y organiza todos los componentes gráficos en la ventana.
        setLocationRelativeTo(null); // Centra la ventana en la pantalla.
        cerrar(); // Llama al método cerrar(), que configura la acción al cerrar la ventana.
        setIconImage(getIconImage()); // Establece un ícono personalizado para la ventana.
    }
    
    //Icono del JFrame
    @Override // Indica que este método sobrescribe el método getIconImage() de la clase JFrame
    
    // Usa Toolkit (una clase de utilidades gráficas de AWT) para obtener una imagen ubicada en la ruta interna del proyecto
    // ClassLoader.getSystemResource() localiza el archivo dentro del classpath (dentro de src o el .jar).
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("workshopadmin/Imagenes/LogoIcono.png"));
        return retValue; // Devuelve la imagen para que sea usada como ícono del JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAdministrador = new javax.swing.JButton();
        jButtonDocente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelInformación = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesón general");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("¡Bienvenido!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("¿Quién desea ingresar?");

        jButtonAdministrador.setBackground(java.awt.Color.lightGray);
        jButtonAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Administrador.png"))); // NOI18N
        jButtonAdministrador.setText("Administrador");
        jButtonAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAdministradorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAdministradorMouseExited(evt);
            }
        });
        jButtonAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministradorActionPerformed(evt);
            }
        });

        jButtonDocente.setBackground(java.awt.Color.lightGray);
        jButtonDocente.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Docente.png"))); // NOI18N
        jButtonDocente.setText("Docente");
        jButtonDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDocenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDocenteMouseExited(evt);
            }
        });
        jButtonDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdministrador))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(jButtonAdministrador)
                .addGap(73, 73, 73)
                .addComponent(jButtonDocente)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Imagenes/Logo.jpg"))); // NOI18N

        jLabelInformación.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Informacion.png"))); // NOI18N
        jLabelInformación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInformaciónMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInformación)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3))
                    .addComponent(jLabelInformación))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cerrar(){
        try {
            // Evita que la ventana se cierre automáticamente al presionar la "X".
            this.setDefaultCloseOperation(JFInicioGeneral.DO_NOTHING_ON_CLOSE);
            // Añade un "escuchador" que detecta cuando se intenta cerrar la ventana.
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    // Cuando se detecta el intento de cierre, se llama al método confirmarSalida().
                    confirmarSalida();
                }
              }
            );
            this.setVisible(true); // Hace visible la ventana (por si no se hizo antes).
        } catch (Exception e) { 
            e.printStackTrace(); // Si ocurre algún error, se imprime el error en consola.
    }
}
    
    public void confirmarSalida(){
        // Muestra un cuadro de diálogo de confirmación al usuario.
        int valor = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea cerrar la aplicación?", 
                "Advertencia", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);
        // Si el usuario hace clic en "Sí", el programa se cierra completamente.
        if (valor==JOptionPane.YES_OPTION){
            System.exit(0); // Termina la ejecución de la aplicación.
        }
    }
    
    private void jButtonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministradorActionPerformed
        // TODO add your handling code here:
        JFInicioAdministrador JFInicioAdministrador =new JFInicioAdministrador(); // Crea una nueva instancia de la ventana para el administrador
                JFInicioAdministrador.setVisible(true); // Muestra la ventana del administrador
                JFInicioAdministrador.setLocationRelativeTo(null); // Centra la ventana
                this.setVisible(false); // Oculta la ventana actual
    }//GEN-LAST:event_jButtonAdministradorActionPerformed

    private void jButtonAdministradorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdministradorMouseEntered
        // TODO add your handling code here:
         // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonAdministrador.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonAdministradorMouseEntered

    private void jButtonAdministradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdministradorMouseExited
        // TODO add your handling code here:
        // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonAdministrador.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonAdministradorMouseExited

    private void jButtonDocenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDocenteMouseEntered
        // TODO add your handling code here:
        // Cambia el fondo del botón a verde cuando el mouse pasa por encima.
        jButtonDocente.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonDocenteMouseEntered

    private void jButtonDocenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDocenteMouseExited
        // TODO add your handling code here:
        // Restaura el fondo del botón a gris claro cuando el mouse sale.
        jButtonDocente.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonDocenteMouseExited

    private void jButtonDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocenteActionPerformed
        // TODO add your handling code here:
        JFInicioDocente JFInicioDocente =new JFInicioDocente(); // Crea una nueva instancia de la ventana para el Docente
                JFInicioDocente.setVisible(true); // Muestra la ventana del docente
                JFInicioDocente.setLocationRelativeTo(null); // Centra la ventana
                this.setVisible(false); // Oculta la ventana actual
    }//GEN-LAST:event_jButtonDocenteActionPerformed

    private void jLabelInformaciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformaciónMouseClicked
        // TODO add your handling code here:
        // Muestra un cuadro de diálogo informativo cuando se hace clic en el ícono de información.
        JOptionPane.showMessageDialog(null,"Por favor, selecciona un tipo de usuario para continuar.",
            "Información",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelInformaciónMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInicioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInicioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInicioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInicioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInicioGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministrador;
    private javax.swing.JButton jButtonDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelInformación;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
