/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicios;

import javax.swing.JOptionPane;
import Administrador.JFMenuAdministrador;
import Clases.Conexion;
import Clases.TextPrompt;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author canto
 */
public class JFInicioAdministrador extends javax.swing.JFrame {

    String bd="workshopadmin";
    String url="jdbc:mysql://localhost:3306/";
    String user="root";
    String password="sqloracle";
    String driver="com.mysql.cj.jdbc.Driver";
    Connection cx=null;
    PreparedStatement ps=null;
    
    /**
     * Creates new form JFInicio
     */
    public JFInicioAdministrador() {
        initComponents();
        jLabelOcultar.setVisible(false);
        TextPrompt usuario = new TextPrompt("22070011",jTextNoControl);
        TextPrompt contrasenia = new TextPrompt("victor1901",jPasswordContraseña);
        
        setIconImage(getIconImage());
    }
    
    //Icono del JFrame
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("workshopadmin/Imagenes/LogoIcono.png"));
        return retValue;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextNoControl = new javax.swing.JTextField();
        jButtonIngresar = new javax.swing.JButton();
        jPasswordContraseña = new javax.swing.JPasswordField();
        jLabelVer = new javax.swing.JLabel();
        jLabelOcultar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión del administrador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Inicio de sesión");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Usuario.png"))); // NOI18N
        jLabel2.setText("No. Control");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 109, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Contraseña.png"))); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 172, -1, -1));

        jTextNoControl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(jTextNoControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 150, 30));

        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonIngresarMouseExited(evt);
            }
        });
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jPasswordContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(jPasswordContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, 30));

        jLabelVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Visible.png"))); // NOI18N
        jLabelVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVerMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 30, 30));

        jLabelOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/NoVisible.png"))); // NOI18N
        jLabelOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOcultarMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 30, 30));

        jButton1.setText("Probar conexión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Imagenes/Logo.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("¡Bienvenido");

        jButtonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegresarMouseExited(evt);
            }
        });
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setText("Administrador!");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshopadmin/Iconos/Informacion.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonRegresar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 23, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRegresar)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        JFInicioGeneral JFUsuarios =new JFInicioGeneral();  
                JFUsuarios.setDefaultCloseOperation(JFUsuarios.EXIT_ON_CLOSE);
                JFUsuarios.setVisible(true);
                JFUsuarios.setLocationRelativeTo(null); // Centra la ventana en la pantalla
                this.setVisible(false); 
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // Método que se ejecuta al presionar el botón "Ingresar"
        if(jTextNoControl.getText().isEmpty()){ //Verifica que el usuario no este vacío
            JOptionPane.showMessageDialog(null,"Inserte su número de control", //Muestra mensaje en caso de estar vacío
            "Error",
            JOptionPane.ERROR_MESSAGE);
            jTextNoControl.requestFocus(); //Regresa el cursor al campo del usuario
        } else { //Si no esta vacío comprueba que la contraseña no este vacía 
            if(jPasswordContraseña.getPassword().length == 0){
                JOptionPane.showMessageDialog(null,"Inserte su contraseña", //Muestra mensaje en caso de estar vacío 
                "Error",
                JOptionPane.ERROR_MESSAGE);
                jPasswordContraseña.requestFocus(); //Regresa el cursor al campo de contraseña
            }else{  
                try // Si ambos campos están llenos
                {
                    Class.forName(driver);  // Carga el driver JDBC necesario para conectar con la base de datos
                    cx=DriverManager.getConnection(url+bd,user, password); 
                    
                    PreparedStatement consulta; // Prepara una consulta SQL segura
                    consulta=cx.prepareStatement("SELECT usuario, contrasenia FROM usuarios WHERE usuario = ?");
                    consulta.setString(1, jTextNoControl.getText()); // Inserta el valor ingresado como parámetro para evitar inyecciones SQL
                    
                    ResultSet resultado = consulta.executeQuery(); // Ejecuta la consulta y guarda el resultado
                    String contraseniaReal = ""; // Variable donde se guardará la contraseña almacenada en la base de datos

                        
                    if(resultado.next())  // Verifica si se encontró un usuario con ese número de control
                    {
                        contraseniaReal=resultado.getString("contrasenia");// Obtiene la contraseña real desde la base de datos
                        String contraseniaCapturada = new String(jPasswordContraseña.getPassword());// Convierte la contraseña ingresada a String

                        
                    if (contraseniaReal.equals(contraseniaCapturada))// Compara la contraseña real con la ingresada
                    {                        
                        JFMenuAdministrador JFMenuAdministrador =new JFMenuAdministrador();   // Crea una instancia del menú de administrador
                        JFMenuAdministrador.setDefaultCloseOperation(JFMenuAdministrador.EXIT_ON_CLOSE);  // Define que al cerrar se finalice la aplicación
                        JFMenuAdministrador.setVisible(true);// Muestra la ventana de administrador
                        JFMenuAdministrador.setLocationRelativeTo(null);  // Centra la ventana en pantalla
                        this.setVisible(false); // Oculta la ventana de inicio de sesión
                    }
                    else // Si la contraseña no coincide
                    {
                        JOptionPane.showMessageDialog(null,"Contraseña incorrecta", // Muestra mensaje de error
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    else{
                            JOptionPane.showMessageDialog(null,"Usuario incorrecto", // Muestra mensaje de error
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                            }
                }
                catch(ClassNotFoundException | SQLException ex) // Captura errores de clase no encontrada o de base de datos
                {
                    System.out.println("No se conectó a la BD" + ex.getMessage());// Muestra el error en consola
                    JOptionPane.showMessageDialog(null, "No se conectó a la BD" + ex.getMessage());// Muestra mensaje de error al usuario
                    Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);// Registra el error en el log con nivel SEVERE
                        } 
                    }
                }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jLabelVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVerMouseClicked
        // TODO add your handling code here:
        jLabelVer.setVisible(false);
        jLabelOcultar.setVisible(true);
        jPasswordContraseña.setEchoChar((char)0);
    }//GEN-LAST:event_jLabelVerMouseClicked

    private void jLabelOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOcultarMouseClicked
        // TODO add your handling code here:
        jLabelVer.setVisible(true);
        jLabelOcultar.setVisible(false);
        jPasswordContraseña.setEchoChar(('*'));       
    }//GEN-LAST:event_jLabelOcultarMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Has click en lo que deseas administrar",
            "Información",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButtonIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngresarMouseEntered
        // TODO add your handling code here:
        jButtonIngresar.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonIngresarMouseEntered

    private void jButtonIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngresarMouseExited
        // TODO add your handling code here:
        jButtonIngresar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonIngresarMouseExited

    private void jButtonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseEntered
        // TODO add your handling code here:
        jButtonRegresar.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonRegresarMouseEntered

    private void jButtonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMouseExited
        // TODO add your handling code here:
        jButtonRegresar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonRegresarMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Conexion con= new Conexion();
        con.conectar();
        con.desconectar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInicioAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelOcultar;
    private javax.swing.JLabel jLabelVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordContraseña;
    private javax.swing.JTextField jTextNoControl;
    // End of variables declaration//GEN-END:variables
}
